---
- hosts: localhost
  gather_facts: no
  vars:
    ami_id: "ami-026dea5602e368e96"
  module_defaults:
    group/aws:
      profile: auburn
      region: "us-west-2"
  tasks:
    - name: Provision M5 EC2 instance
      ec2:
        key_name: raven
        group: Module5-developer-sg
        instance_type: t3.nano
        image: "{{ ami_id }}"
        instance_tags:
          Name: Module 5 First Instance
          Module: 5
        wait: yes
        vpc_subnet_id: "{{ public_subnet.subnet.id }}"
        assign_public_ip: yes
        exact_cout: 1
        count_tag:
          Name: Module 5 First Instance
